apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesStrategicMerge:
  - StatefulSet-add-claim.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: nextcloud-mariadb
    path: StatefulSet-remove-volume.yaml
