apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-database
spec:
  template:
    spec:
      initContainers:
        - name: create-lost-n-found
          image: busybox
          command:
            - sh
            - -c
            - mkdir -p /data/lost+found
          volumeMounts:
            - name: database
              mountPath: /data
