apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-backup-duplicity
resources:
  - namespace.yaml
  - PV-nextcloud-dnas.yaml
  - PVC-nextcloud-application.yaml
  - PVC-nextcloud-database.yaml
  - PVC-nextcloud-dnas.yaml
  - ../../base
components:
  - ../../components/backup-duplicity
patchesStrategicMerge:
  - Deployment-application-fix-lostNfound.yaml
  - Deployment-database-add-lostNfound.yaml
