apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-dnas
spec:
  storageClassName: samba
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  mountOptions:
    - uid=33
    - gid=33
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: nextcloud-dnas
    volumeAttributes:
      source: //dnas-smb.homecloud.svc.cluster.local/dnas
    nodeStageSecretRef:
      name: dnas-smb
      namespace: homecloud