apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-dnas
spec:
  volumeName: nextcloud-dnas
  storageClassName: samba
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
