apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibreweb-books
spec:
  volumeName: calibreweb-books
  storageClassName: samba
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
