---

- name: test-mariadb-claim-templates - apply
  shell: |
    set -eo pipefail
    /tmp/hck/kustomize build ../../modules/nextcloud/overlays/test-mariadb-claim-templates \
      | /tmp/hck/kubectl --context kind-{{ kind_cluster_name }} apply -f-
  args:
    executable: /bin/bash
    warn: false
  register: apply_manifest
  changed_when: false

- name: test-mariadb-claim-templates - wait for nextcloud
  command: /tmp/hck/kubectl --context kind-{{ kind_cluster_name }} \
    get statefulsets.apps tmct-nextcloud \
    -o jsonpath='{.status.readyReplicas}'
  changed_when: false
  register: kubectl_get_nextcloud
  delay: 3
  retries: 40
  until: "'1' in kubectl_get_nextcloud.stdout"
