apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: calibreweb
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`calibreweb.home.cloud`)
      kind: Rule
      services:
        - name: calibreweb
          port: 80
