---

- hosts: localhost
  tasks:
    - include_tasks: ./verify/test-claimed-volumes.yml
    - include_tasks: ./verify/test-redis-ingress-traefik.yml
    - include_tasks: ./verify/test-mariadb-claimed-volumes.yml
    #- include_tasks: ./verify/test-longhorn-mounts.yml
