apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kustomize.morin.io/module: homecloud-nextcloud
  kustomize.morin.io/version: 0.1.2
vars:
  - name: PUBLIC_DOMAIN
    objref:
      kind: ConfigMap
      version: v1
      name: common
    fieldref:
      fieldpath: data.PUBLIC_DOMAIN
  - name: SERVICE_APPLICATION_NAME
    objref:
      kind: Service
      version: v1
      name: nextcloud-application
    fieldref:
      fieldpath: metadata.name
  - name: SERVICE_CACHE_NAME
    objref:
      kind: Service
      version: v1
      name: nextcloud-cache
    fieldref:
      fieldpath: metadata.name
  - name: SERVICE_DATABASE_NAME
    objref:
      kind: Service
      version: v1
      name: nextcloud-database
    fieldref:
      fieldpath: metadata.name
resources:
  - Deployment-application.yaml
  - Deployment-cache.yaml
  - Deployment-database.yaml
  - CronJob-cron.yaml
  - Service-application.yaml
  - Service-cache.yaml
  - Service-database.yaml
configMapGenerator:
  - name: application
    envs:
      - Configmap-application.env
  - name: common
    envs:
      - Configmap-common.env
secretGenerator:
  - name: application
    envs:
      - Secret-application.env
  - name: common
    envs:
      - Secret-common.env
  - name: database
    envs:
      - Secret-database.env
