apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud-application
  name: nextcloud-application
spec:
  selector:
    app: nextcloud-application
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: nextcloud
      protocol: TCP
