apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud-database
  name: nextcloud-database
spec:
  selector:
    app: nextcloud-database
  type: ClusterIP
  ports:
    - name: service
      port: 3306
      targetPort: mariadb
      protocol: TCP
