apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-server
spec:
  template:
    spec:
      containers:
        - name: nextcloud
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - mysqladmin status -uroot -p"${MYSQL_ROOT_PASSWORD}" && ls /var/lib/mysql/lost+found
