apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud
spec:
  template:
    spec:
      containers:
        - name: nextcloud
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - curl -fH host:${PUBLIC_DOMAIN} http://localhost/status.php && ls /var/www/html/lost+found
