apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibreweb-config
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
