apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

vars:
  - name: SERVICE_REDIS_NAME
    objref:
      kind: Service
      version: v1
      name: nextcloud-redis
    fieldref:
      fieldpath: metadata.name

resources:
  - StatefulSet-redis.yaml
  - Service-redis.yaml

patchesStrategicMerge:
  - StatefulSet-env.yaml
