apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud-redis
  name: nextcloud-redis
spec:
  selector:
    app: nextcloud-redis
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
