apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: nextcloud-redis
  name: nextcloud-redis
spec:
  serviceName: nextcloud-redis
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-redis
  template:
    metadata:
      labels:
        app: nextcloud-redis
    spec:
      containers:
        - name: redis
          image: redis:5-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            exec:
              command:
                - redis-cli
                - ping
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            exec:
              command:
                - redis-cli
                - ping
