apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homecloud
namePrefix: hc-

resources:
  - PV-calibreweb-dnas.yaml
  - PVC-calibreweb-dnas.yaml
  - PVC-calibreweb-config.yaml
  - ../../base

components:
  - ../../components/homecloud-volumes

patchesStrategicMerge:
  - StatefulSet-add-initContainer.yaml
