apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibreweb
spec:
  template:
    spec:
      initContainers:
        - name: initialization
          image: busybox
          command:
            - sh
            - -c
            - mkdir -p /config/lost+found /dnas/syncthing/books
          volumeMounts:
            - name: config
              mountPath: /config
            - name: dnas
              mountPath: /dnas
