apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: gitea
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`gitea.home.cloud`)
      kind: Rule
      services:
        - name: gitea
          port: 80
