apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-mariadb
spec:
  template:
    spec:
      volumes:
        - name: data
          emptyDir:
          persistentVolumeClaim:
            claimName: nextcloud-mariadb-data
