apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kustomize.morin.io/module: calibreweb
  kustomize.morin.io/version: 0.1.2
resources:
  - Service-application.yaml
  - Deployment-application.yaml
configMapGenerator:
  - name: application
    envs:
      - Configmap-application.env
