apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homecloud

resources:
  - ../../base
  - PV-calibre-books.yaml

components:
  - ../../components/claimed-volumes
  - ../../components/homecloud-claims

patchesStrategicMerge:
  - StatefulSet-add-lostNfound.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: calibreweb
    path: StatefulSet-skip-longhorn.yaml
