apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-redis-ingress-traefik

resources:
  - namespace.yaml
  - ../../base

components:
  - ../../components/ingress-traefik
  - ../../components/redis
