apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibreweb
spec:
  template:
    spec:
      volumes:
        - name: config
          emptyDir:
          persistentVolumeClaim:
            claimName: calibreweb-config
        - name: books
          emptyDir:
          persistentVolumeClaim:
            claimName: calibreweb-books
