apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibreweb
spec:
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: config
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: books
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
