apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud
spec:
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 512Mi
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: dnas
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
