apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
spec:
  template:
    spec:
      containers:
        - name: gitea
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - curl -f http://localhost:3000/version && ls /data/lost+found
