apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nextcloud-application
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`nextcloud.home.cloud`)
      kind: Rule
      services:
        - name: nextcloud-application
          port: 80
