apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kustomize.morin.io/module: calibreweb
  kustomize.morin.io/version: 0.1.0-alpha.0
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: calibreweb
    envs:
      - configmap.env
