apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  kustomize.morin.io/module: calibreweb
  kustomize.morin.io/version: 0.1.0

resources:
  - Service.yaml
  - StatefulSet.yaml

configMapGenerator:
  - name: calibreweb
    envs:
      - configmap.env
