apiVersion: v1
kind: Service
metadata:
  labels:
    app: calibreweb
  name: calibreweb
spec:
  selector:
    app: calibreweb
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
