apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibreweb
spec:
  template:
    spec:
      containers:
        - name: calibreweb
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                - curl -f http://localhost:8083 && ls /config/lost+found
