apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesStrategicMerge:
  - StatefulSet-mariadb-livenessProbe.yaml
  - StatefulSet-mariadb-add-claims.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: nextcloud-mariadb
    path: StatefulSet-mariadb-remove-volumes.yaml
