apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

vars:
  - name: SERVICE_MARIADB_NAME
    objref:
      kind: Service
      version: v1
      name: nextcloud-mariadb
    fieldref:
      fieldpath: metadata.name

resources:
  - deployment-mariadb.yaml
  - service-mariadb.yaml

patchesStrategicMerge:
  - deployment-initContainers.yaml
  - deployment-env.yaml

patchesJson6902:
  - target:
      kind: Deployment
      name: nextcloud
      version: v1
      group: apps
    path: deployment-envFrom.yaml

configMapGenerator:
  - name: common
    behavior: merge
    envs:
      - configmap-common.env

secretGenerator:
  - name: common
    behavior: merge
    envs:
      - secret-common.env
  - name: mariadb
    behavior: create
    envs:
      - secret-mariadb.env
