apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud-mariadb
  name: nextcloud-mariadb
spec:
  selector:
    app: nextcloud-mariadb
  type: ClusterIP
  ports:
    - name: mariadb
      port: 3306
      targetPort: mysql
      protocol: TCP
