apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud
spec:
  template:
    spec:
      containers:
        - name: nextcloud
          env:
            - name: MYSQL_HOST
              value: $(SERVICE_MARIADB_NAME)
