apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-database
          image: mariadb:10.4
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_HOST
              value: $(SERVICE_MARIADB_NAME)
          envFrom:
            - configMapRef:
                name: common
                optional: false
            - secretRef:
                name: common
                optional: false
          command:
            - sh
            - -c
            - until mysql --host=${MYSQL_HOST} --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute='SELECT 1;'; do echo waiting for database; sleep 2; done;
