apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextcloud-server
  name: nextcloud-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud-server
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:stable
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          env:
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: $(PUBLIC_DOMAIN)
            - name: MYSQL_HOST
              value: $(SERVICE_DATABASE_NAME)
            - name: REDIS_HOST
              value: $(SERVICE_CACHE_NAME)
          envFrom:
            - configMapRef:
                name: nextcloud-common
                optional: false
            - secretRef:
                name: nextcloud-common
                optional: false
            - configMapRef:
                name: nextcloud-server
                optional: false
            - secretRef:
                name: nextcloud-server
                optional: false
          volumeMounts:
            - name: data
              mountPath: /var/www/html
            - name: dnas
              mountPath: /mnt/dnas
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            exec:
              command:
                - bash
                - -c
                - curl -fH host:${PUBLIC_DOMAIN} http://localhost/status.php
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            exec:
              command:
                - bash
                - -c
                - curl -fH host:${PUBLIC_DOMAIN} http://localhost/status.php
      initContainers:
        - name: wait-for-database
          image: mariadb:10.4
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_HOST
              value: $(SERVICE_DATABASE_NAME)
          envFrom:
            - configMapRef:
                name: nextcloud-common
                optional: false
            - secretRef:
                name: nextcloud-common
                optional: false
          command:
            - sh
            - -c
            - until mysql --host=${MYSQL_HOST} --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute='SELECT 1;'; do echo waiting for database; sleep 2; done;
      volumes:
        - name: data
          emptyDir: { }
        - name: dnas
          emptyDir: { }
