apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  kustomize.morin.io/module: nextcloud
  kustomize.morin.io/version: 0.1.0-alpha.0

vars:
  - name: PUBLIC_DOMAIN
    objref:
      kind: ConfigMap
      version: v1
      name: nextcloud-common
    fieldref:
      fieldpath: data.PUBLIC_DOMAIN
  - name: SERVICE_SERVER_NAME
    objref:
      kind: Service
      version: v1
      name: nextcloud-server
    fieldref:
      fieldpath: metadata.name
  - name: SERVICE_DATABASE_NAME
    objref:
      kind: Service
      version: v1
      name: nextcloud-database
    fieldref:
      fieldpath: metadata.name
  - name: SERVICE_CACHE_NAME
    objref:
      kind: Service
      version: v1
      name: nextcloud-cache
    fieldref:
      fieldpath: metadata.name

resources:
  - cronjob.yaml
  - deployment-cache.yaml
  - deployment-database.yaml
  - deployment-server.yaml
  - service-cache.yaml
  - service-database.yaml
  - service-server.yaml

configMapGenerator:
  - name: nextcloud-server
    envs:
      - configmap-server.env
  - name: nextcloud-common
    envs:
      - configmap-common.env

secretGenerator:
  - name: nextcloud-server
    envs:
      - secret-server.env
  - name: nextcloud-common
    envs:
      - secret-common.env
  - name: nextcloud-database
    envs:
      - secret-database.env
