apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  kustomize.morin.io/module: nextcloud
  kustomize.morin.io/version: 0.1.2
vars:
  - name: PUBLIC_DOMAIN
    objref:
      kind: ConfigMap
      version: v1
      name: common
    fieldref:
      fieldpath: data.PUBLIC_DOMAIN
  - name: SERVICE_NEXTCLOUD_NAME
    objref:
      kind: Service
      version: v1
      name: nextcloud
    fieldref:
      fieldpath: metadata.name
resources:
  - CronJob.yaml
  - StatefulSet.yaml
  - Service.yaml
configMapGenerator:
  - name: nextcloud
    envs:
      - configmap-nextcloud.env
  - name: common
    envs:
      - configmap-common.env
secretGenerator:
  - name: common
    envs:
      - secret-common.env
  - name: nextcloud
    envs:
      - secret-server.env
