apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud-cache
  name: nextcloud-cache
spec:
  selector:
    app: nextcloud-cache
  type: ClusterIP
  ports:
    - name: cache
      port: 6379
      targetPort: redis
      protocol: TCP
