apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud
  name: nextcloud
spec:
  selector:
    app: nextcloud
  type: ClusterIP
  ports:
    - name: nextcloud
      port: 80
      targetPort: web
      protocol: TCP
