apiVersion: v1
kind: Service
metadata:
  labels:
    app: nextcloud-server
  name: nextcloud-server
spec:
  selector:
    app: nextcloud-server
  type: ClusterIP
  ports:
    - name: nextcloud
      port: 80
      targetPort: web
      protocol: TCP
