apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud-mariadb
spec:
  template:
    spec:
      initContainers:
        - name: create-lost-n-found
          image: busybox
          command:
            - sh
            - -c
            - mkdir /data/lost+found
          volumeMounts:
            - name: data
              mountPath: /data
