apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: tcv-

resources:
  - ../../base
  - pvc-database.yaml
  - pvc-dnas.yaml
  - pvc-server.yaml

components:
  - ../../components/claimed-volumes
