apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: tcv-

resources:
  - ../../base
  - PVC-nextcloud-data.yaml
  - PVC-nextcloud-dnas.yaml

components:
  - ../../components/claimed-volumes
