apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: calibreweb
spec:
  template:
    spec:
      containers:
        - name: calibreweb
          volumeMounts:
            - mountPath: /books
              name: dnas
              subPath: syncthing/books
      volumes:
        - name: config
          emptyDir:
          persistentVolumeClaim:
            claimName: calibreweb-config
        - name: books
        - name: dnas
          persistentVolumeClaim:
            claimName: calibreweb-dnas
