apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  kustomize.morin.io/module: gitea
  kustomize.morin.io/version: 0.1.0-alpha.0

vars:
  - name: PUBLIC_DOMAIN
    objref:
      kind: ConfigMap
      version: v1
      name: gitea
    fieldref:
      fieldpath: data.DOMAIN

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: gitea
    envs:
      - configmap.env
