apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitea
  name: gitea
spec:
  selector:
    app: gitea
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
    - name: ssh
      port: 22
      targetPort: ssh
      protocol: TCP
