apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-data
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
