apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitea
spec:
  template:
    spec:
      volumes:
        - name: data
          emptyDir:
          persistentVolumeClaim:
            claimName: gitea-data
