apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: tcv-

resources:
  - ../../base
  - PVC-calibreweb-books.yaml
  - PVC-calibreweb-config.yaml

components:
  - ../../components/claimed-volumes
