apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: test-mariadb-claimed-volumes

resources:
  - namespace.yaml
  - ../../base
  - pvc-nextcloud-data.yaml
  - pvc-nextcloud-dnas.yaml
  - pvc-nextcloud-mariadb-data.yaml

components:
  - ../../components/claimed-volumes
  - ../../components/mariadb
  - ../../components/mariadb-claimed-volumes
