---

- name: test-claimed-volumes - get pv
  command: /tmp/hck/kubectl --context kind-{{ kind_cluster_name }} get pv \
    -ojsonpath="{range .items[*]}[{.spec.claimRef.name} {.status.phase} {.spec.storageClassName}] {end}"
  args:
    warn: false
  register: get_pv

- name: test-claimed-volumes - get pvc
  command: /tmp/hck/kubectl --context kind-{{ kind_cluster_name }} get pvc \
    -ojsonpath="{range .items[*]}[{.metadata.name} {.status.phase}] {end}"
  args:
    warn: false
  register: get_pvc

- name: test-claimed-volumes - assert
  assert:
    quiet: true
    that:
      - "'[tcv-nextcloud-database Bound standard]' in get_pv.stdout"
      - "'[tcv-nextcloud-dnas Bound standard]' in get_pv.stdout"
      - "'[tcv-nextcloud-server Bound standard]' in get_pv.stdout"
      - "'[tcv-nextcloud-database Bound]' in get_pvc.stdout"
      - "'[tcv-nextcloud-dnas Bound]' in get_pvc.stdout"
      - "'[tcv-nextcloud-server Bound]' in get_pvc.stdout"
