---

- name: mariadb-claimed-volumes - get pv
  command: /tmp/hck/kubectl --context kind-{{ kind_cluster_name }} \
    get pv -n test-mariadb-claimed-volumes \
    -ojsonpath="{range .items[*]}[{.spec.claimRef.name} {.status.phase} {.spec.storageClassName}] {end}"
  args:
    warn: false
  register: get_pv

- name: mariadb-claimed-volumes - get pvc
  command: /tmp/hck/kubectl --context kind-{{ kind_cluster_name }} \
    get pvc -n test-mariadb-claimed-volumes \
    -ojsonpath="{range .items[*]}[{.metadata.name} {.status.phase}] {end}"
  args:
    warn: false
  register: get_pvc

- name: mariadb-claimed-volumes - assert
  assert:
    quiet: true
    that:
      - "'[nextcloud-mariadb-data Bound standard]' in get_pv.stdout"
      - "'[nextcloud-dnas Bound standard]' in get_pv.stdout"
      - "'[nextcloud-data Bound standard]' in get_pv.stdout"
      - "'[nextcloud-mariadb-data Bound]' in get_pvc.stdout"
      - "'[nextcloud-dnas Bound]' in get_pvc.stdout"
      - "'[nextcloud-data Bound]' in get_pvc.stdout"
