apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 512Mi
